aws_region = "your aws region"
aws_account_id = "your aws accound id"
user_bucket = "user-content-bucket-xxxx"
lambda_function_name = "FileUploaderLambda"
lambda_runtime = "python3.8"
webapp_bucket = "file-uploader-service-app-xxxx"